server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: motorbike-service
          uri: http://${MOTORBIKE_SERVICE_BASEURL:motorbike-service:8080}
          predicates:
            - Path=/motorbikes/**
          filters:
            - RewritePath=/motorbikes/(?<segment>.*), /${segment}

        - id: client-service
          uri: http://${CLIENT_SERVICE_BASEURL:client-service:8081}
          predicates:
            - Path=/clients/**
          filters:
            - RewritePath=/clients/(?<segment>.*), /${segment}

        - id: reservation-service
          uri: http://${RESERVATION_SERVICE_BASEURL:reservation-service:8082}
          predicates:
            - Path=/reservations/**
          filters:
            - RewritePath=/reservations/(?<segment>.*), /${segment}
