name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        options: --health-cmd='curl --silent --fail localhost:27017 || exit 1' --health-interval=30s --health-timeout=30s --health-retries=3

      motorbike-db:
        image: mysql:latest
        container_name: motorbike-db
        ports:
          - "3307:3306"
        environment:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: motorbikeDB
        volumes:
          - motorbike-data:/var/lib/mysql
        options: --health-cmd='curl --silent --fail localhost:3306 || exit 1' --health-interval=30s --health-timeout=30s --health-retries=3

      client-db:
        image: mysql:latest
        container_name: client-db
        ports:
          - "3308:3306"
        environment:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: clientDB
        volumes:
          - client-data:/var/lib/mysql
        options: --health-cmd='curl --silent --fail localhost:3306 || exit 1' --health-interval=30s --health-timeout=30s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: |
          docker build -t r0880734/motorbike-service ./motorbike-service
          docker build -t r0880734/reservation-service ./reservation-service
          docker build -t r0880734/client-service ./client-service

      - name: Run services using Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Wait for services to be ready
        run: |
          # Give services time to start up (adjust timing if necessary)
          sleep 30

      - name: Run tests
        run: |
          docker exec motorbike-service ./mvnw test
          docker exec reservation-service ./mvnw test
          docker exec client-service ./mvnw test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images to Docker Hub
        run: |
          docker push r0880734/motorbike-service
          docker push r0880734/reservation-service
          docker push r0880734/client-service

      - name: Deploy to Production Server
        run: |
          # Example deployment using SSH to a remote server
          scp -i ${{ secrets.SERVER_SSH_KEY }} docker-compose.yml user@yourserver:/path/to/deploy
          ssh -i ${{ secrets.SERVER_SSH_KEY }} user@yourserver 'cd /path/to/deploy && docker-compose down && docker-compose up -d'

      - name: Verify Deployment
        run: |
          ssh -i ${{ secrets.SERVER_SSH_KEY }} user@yourserver 'curl http://localhost:8080/motorbikes && curl http://localhost:8080/reservations && curl http://localhost:8080/clients'

volumes:
  motorbike-data:
  reservation-data:
  client-data:
